<div class="container-fluid">
    <div class="row" style="padding: 5%;">

        <h1 class="h2 text-center py-3">Products</h1>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Product Name</th>
                        <th scope="col">Product Category</th>
                        <th scope="col">Product Price</th>
                        <th scope="col">Product Stock</th>
                        <th scope="col">Details</th>
                        <th scope="col">Edit</th>
                        <th scope="col">DELETE</th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    for ($i = 0; $i < count($data); $i++) {
                        $one = (array)$data[$i];
                        $id = $one["_id"];
                    ?>
                        <tr>
                            <td> <?php echo $one["Name"] ?></td>
                            <td> <?php echo $one["Category"]  ?></td>
                            <td> <?php echo $one["price"] ?></td>
                            <td> <?php echo $one["stock"] ?></td>
                            <td>
                                <button type="button" class="btn btn-success modalBtn" data-id="<?php echo $id ?>" data-toggle="modal" data-target="#exampleModal">Quick View</button>
                            </td>
                            <td>
                                <?php
                                echo  $this->tag->linkTo(
                                    [
                                        "products/edit?id=$id",
                                        "EDIT",
                                        "class" => "btn btn-primary"
                                    ]
                                );
                                ?>
                            </td>
                            <td>
                                <?php echo $this->tag->linkTo(
                                    [
                                        "products/delete?id=$id",
                                        "DELETE",
                                        "class" => "btn btn-danger"
                                    ]
                                );
                                ?>
                            </td>
                        </tr> <?php
                            }
                                ?>
                </tbody>
            </table>
        </div>


        <div class="form-floating">
            <?php echo $this->tag->linkTo(["products", "Add New Product", "class" => "btn btn-lg btn-primary"]); ?>
        </div>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Quick View</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="variations">
                        <div class="row">
                            <div class="col-md-5">
                            <p class="text-center" id = "variations"></p>
                            </div>
                            <div class="col-md-5">
                            <p class="text-center" id="additional"></p>
                            </div>
                        </div>
                       
                       
                    </div>
                    </main>
                </div>
            </div>


            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

            <!-- Latest compiled JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
            <script src="../../../public/assets/js/script2.js"></script>