<div class="container-fluid">
    <div class="row" style="padding: 5%;">
        <h1 class="h2 text-center py-3">Orders</h1>
        <!----------------------------------------------- Filter ---------------------------------------->
        <form action="" method="post">
            <div class="col-md-3" id="filter">

                <select class='form-control' name="status" id="option">
                    <option selected hidden disabled>Filter By Status</option>
                    <option>Paid</option>
                    <option>Processing</option>
                    <option>Dispatched</option>
                    <option>Shipped</option>
                    <option>Refunded</option>
                </select>
            </div>
            <div class="col-md-3" id="filter_date">
                <select class='form-control  dateSelected' name="date" id="option_dates">
                    <option selected hidden disabled>Filter By Date</option>
                    <option value="-1 day">Today</option>
                    <option value="last Sunday">This Week</option>
                    <option value="first day of this month">This Month</option>
                    <option value="Custom">Custom</option>


                </select>
            </div>



            <button class="btn btn-danger" name="Filter" style="width: 10%;" type="submit">Apply Filters</button>
            <br>
            <div id="customDiv" style="margin-left:26.5%;display:none;">
                <p> <?php echo $this->tag->textField(["start","placeholder"=>"start date", "class" => "pricetag", "style"=>"width:15%;"]); ?>
                    <?php echo $this->tag->textField(["end", "placeholder"=>"end date","class" => "pricetag", "style"=>"width:15%;"]); ?>
                </p>

            </div>
        </form>
        <!----------------------------------------------  Filter end ----------------------->

        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Customer Name</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Varient</th>
                        <th scope="col">Total Price</th>
                        <th scope="col">Date</th>
                        <th scope="col">Status</th>
                        <th scope="col">EDIT Status</th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    for ($i = 0; $i < count($data); $i++) {
                        $one = (array)$data[$i];
                        $id = $one["_id"];
                    ?>
                        <tr>
                            <td> <?php echo $one["Name"] ?></td>
                            <td> <?php echo $one["product"]  ?></td>
                            <td> <?php echo $one["quantity"] ?></td>
                            <td> <?php echo $one["varient"] ?></td>
                            <td> <?php echo $one["total"] ?></td>
                            <td> <?php echo $one["date"] ?></td>
                            <td> <?php echo $one["status"] ?></td>
                            <td>
                                <select name="status" class="w-100 p-2 statusSelected text-center">
                                    <option value="">Change Status</option>
                                    <option data-id='<?php echo $id ?>'>Paid</option>
                                    <option data-id='<?php echo $id ?>'>Processing</option>
                                    <option data-id='<?php echo $id ?>'>Dispatched</option>
                                    <option data-id='<?php echo $id ?>'>Shipped</option>
                                    <option data-id='<?php echo $id ?>'>Refunded</option>
                                </select>
                            </td>
                        </tr> <?php
                            }
                                ?>
                </tbody>
            </table>
        </div>



        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Quick View</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="variations">
                        <div class="row">
                            <div class="col-md-5">
                                <p class="text-center" id="variations"></p>
                            </div>
                            <div class="col-md-5">
                                <p class="text-center" id="additional"></p>
                            </div>
                        </div>


                    </div>
                    </main>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="../../../public/assets/js/scriptOrder.js"></script>